POST http://localhost:8787/api/music/search HTTP/1.1
Content-Type: "application/json"

{
  "keyword": "周杰伦",
  "page": 1
}


POST http://localhost:8787/api/music/get-song HTTP/1.1
Content-Type: "application/json"

{
  "album-id": "40769583",
  "hash": "3FE169AC4EEB69371DFD0A80F6B462EC"
}


POST http://localhost:8787/api/music/get-lyric HTTP/1.1
Content-Type: "application/json"

{
  "keyword": "蒋雪璇",
  "hash": "5BBD95CB7ADFCE00C95D7BAE056687DD",
  "duration": 181
}


POST http://localhost:8787/api/music/get-cover HTTP/1.1
Content-Type: "application/json"

{
  "hash": "81A9D30807DB85C15BD05131E7247DFB"
}

